-----Private Variables-----
local Players = game:GetService("Players") 
local ServerStorage = game:GetService("ServerStorage") 
local RS = game:GetService("ReplicatedStorage")
local Players_Folder: Folder = ServerStorage:FindFirstChild("Players")
local TR: string = "TimeRemaining"
local RagdollTR: string = "RagdollTR"
local IsBlockingName: string = "Block"


local module = {}
-----Public Functions-----
function module:CreateHitbox(character: Model, ) 




end

return module